version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
        - ./mysql/datadir:/var/lib/mysql
    env_file:
        - ./mysql/db-variables-root.env
        - ./mysql/db-variables.env
    networks:
      - misitio-network

  web:
    image: httpd:latest
    ports:
        - "80:80"
    volumes:
        - ./code7:/usr/local/apache2/htdocs/
        - ./code5:/usr/local/apache2/htdocs/v5/
        - ./apache/httpd-min.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - misitio-network

  php5:
    build: ./php5.6
    volumes:
        - ./code5:/var/www/html5/
    env_file:
        - ./mysql/db-variables.env
    depends_on:
        - db
    networks:
      - misitio-network

  php7:
    build: ./php7.1
    volumes:
        - ./code7:/var/www/html/
    networks:
      - misitio-network

networks:
  misitio-network:
    driver: bridge
